name: Packacge update integration

on:
  pull_request:
    branches: [master]
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps: 
      - uses: action/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test
      - run: npm run build